version: '3.8'

services:
  # Django Web (Admin panel, API va Telegram Webhook barchasi shu yerda)
  web:
    build: .
    command: gunicorn --workers 3 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 config.asgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always

volumes:
  static_volume:
