# Generated by Django 5.2.2 on 2025-07-09 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_privategroup_botuser_created_at_alter_botuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_chat_id', models.BigIntegerField(verbose_name='Mijoz Telegram ID')),
                ('c_name', models.CharField(max_length=100, verbose_name='Mijoz ismi')),
                ('c_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mijoz username')),
                ('c_count', models.IntegerField(blank=True, null=True, verbose_name='Yo‘lovchilar soni')),
                ('c_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mijoz telefoni')),
                ('c_direction', models.CharField(blank=True, max_length=255, null=True, verbose_name="Yo'nalishi")),
                ('d_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Haydovchi ismi')),
                ('d_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Haydovchi telefoni')),
                ('d_id', models.BigIntegerField(blank=True, null=True, verbose_name='Haydovchi Telegram ID')),
                ('status', models.BooleanField(default=False, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doer', models.CharField(max_length=200, verbose_name='Bajaruvchi')),
                ('status', models.CharField(max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bot.order')),
            ],
        ),
    ]
