# Generated by Django 5.2.2 on 2025-07-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_order_orderhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='progress', max_length=10, null=True, verbose_name='Holati'),
        ),
    ]
