# Generated by Django 5.2.2 on 2025-07-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('progress', 'Jarayonda'), ('calling', 'Qo‘ng‘iroq qilinmoqda'), ('complete', 'Bajarildi'), ('cancel', 'Bekor qilindi')], default='progress', max_length=10, verbose_name='Holati'),
        ),
    ]
