# Generated by Django 5.2.2 on 2025-07-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='group_chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Guruh chat ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='group_message_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Guruhdagi xabar ID'),
        ),
    ]
