# Generated by Django 5.2.2 on 2025-07-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_order_group_chat_id_order_group_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='c_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Yo‘lovchilar soni'),
        ),
    ]
