# Generated by Django 5.2.2 on 2025-07-20 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_order_c_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=500)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('limit_per_ticket_count', models.IntegerField(default=4)),
                ('limit_per_ticket', models.IntegerField(default=2)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('f_to_t', 'Fargʻona → Toshkent'), ('t_to_f', 'Toshkent → Fargʻona')], max_length=50, verbose_name='Yo‘nalish')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('full', 'To‘lgan'), ('closed', 'Yopilgan')], default='open', max_length=10, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.driver', verbose_name='Haydovchi')),
            ],
            options={
                'verbose_name': 'Chiptalar',
                'verbose_name_plural': "Chiptalar ro'yxati",
            },
        ),
        migrations.CreateModel(
            name='TicketDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Yo‘lovchi F.I.Sh.')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefon raqam')),
                ('count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Yo‘lovchilar soni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqti')),
            ],
            options={
                'verbose_name': 'Chiptadagi buyurtma',
                'verbose_name_plural': 'Chiptadagi buyurtmalar',
            },
        ),
        migrations.DeleteModel(
            name='BotUser',
        ),
        migrations.AddField(
            model_name='order',
            name='user_chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Foydalanuvchi chat ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_message_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Foydalanuvchi xabar ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='c_name',
            field=models.CharField(max_length=255, verbose_name='Mijoz ismi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='c_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mijoz telefoni'),
        ),
        migrations.AddField(
            model_name='ticketdetail',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.order', verbose_name='Buyurtma'),
        ),
        migrations.AddField(
            model_name='ticketdetail',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='bot.ticket', verbose_name='Chipta'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketdetail',
            unique_together={('ticket', 'order')},
        ),
    ]
