# Generated by Django 5.2.2 on 2025-07-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_driver_ticket_ticketdetail_delete_botuser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Haydovchi', 'verbose_name_plural': 'Haydovchilar'},
        ),
        migrations.RemoveField(
            model_name='driver',
            name='limit_per_ticket',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='limit_per_ticket_count',
        ),
        migrations.AddField(
            model_name='driver',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cheklov davomiyligi'),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='driver',
            name='limit_count_per_target',
            field=models.IntegerField(default=4, verbose_name='Yo‘lovchilar limiti (1 ta ticket uchun)'),
        ),
        migrations.AddField(
            model_name='driver',
            name='limit_target_per_24hours',
            field=models.IntegerField(default=2, verbose_name='Kunlik ticket limiti'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balans'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='chat_id',
            field=models.CharField(max_length=20, verbose_name='Chat ID'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ro‘yxatdan o‘tgan vaqt'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='full_name',
            field=models.CharField(max_length=500, verbose_name='To‘liq ism'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Faol'),
        ),
    ]
