# Generated by Django 5.2.2 on 2025-07-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_driver_options_remove_driver_limit_per_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status1',
            field=models.BooleanField(default=True, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Blok'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='limit_count_per_target',
            field=models.IntegerField(default=4, verbose_name='Yo‘lovchi limiti'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='limit_target_per_24hours',
            field=models.IntegerField(default=2, verbose_name="Yo'nalish limiti"),
        ),
    ]
