# Generated by Django 5.2.2 on 2025-07-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_ticket_status1_alter_driver_is_blocked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status1',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Holat'),
        ),
    ]
