# Generated by Django 5.2.2 on 2026-02-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_remove_ticket_status1_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('progress', 'Jarayonda'), ('calling', 'Qo‘ng‘iroq qilinmoqda'), ('accept', 'Bajarildi'), ('reject', 'Bekor qilindi')], default='progress', max_length=10, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='direction',
            field=models.CharField(choices=[('🚖 Beshariqdan Toshkentga', '🚖 Beshariqdan Toshkentga'), ('🚖 Toshkentdan Beshariqga', '🚖 Toshkentdan Beshariqga')], max_length=50, verbose_name='Yo‘nalish'),
        ),
    ]
