# Generated by Django 5.2.2 on 2026-03-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_alter_order_status_alter_ticket_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='last_reply_msg_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Oxirgi reply klaviatura ID'),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_ticket_msg_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Oxirgi ticket xabari ID'),
        ),
    ]
